spring:
  h2:
    console:
      enabled: true

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/book_manager
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        format_sql: true
        ddl-auto: create-drop
    #    defer-datasource-initialization: true
    generate-ddl: false
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
logging:
  level:
    org:
      hibernate:
        sql: debug
