spring:
  h2:
    console:
      enabled: true

  datasource:
    driver-class-name: org.h2.Driver
    username: sa
    password:
    url:
  jpa:
    properties:
      hibernate:
        format_sql: true
        show-sql: true
    #    defer-datasource-initialization: true
    database-platform: org.hibernate.dialect.H2Dialect
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
logging:
  level:
    sql: debug
