spring:
  h2:
    console:
      enabled: true

  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost:3306/book_manager
  jpa:
    database-platform: org.hibernate.dialect.MySQL5Dialect
    properties:
      hibernate:
        ddl-auto: create-drop
        format_sql: true
        show-sql: true
    #    defer-datasource-initialization: true
    generate-ddl: true
#  sql:
#    init:
#      mode: always
#      data-locations: classpath:data.sql
logging:
  level:
    sql: debug
